services:
  # The Serverpod backend API
  - type: web
    name: dwellly-api
    runtime: docker
    rootDir: . # Needs to build from root because of Dart 3.8 workspaces
    dockerfilePath: dwellly_server/Dockerfile
    dockerContext: . # Use repo root as Docker build context so dwellly_client/ is accessible
    plan: free # Can be updated to starter
    envVars:
      - key: runmode
        value: production
      - key: PORT
        value: 8080

      # Serverpod requires these generated keys via Blueprint prompts
      - key: SERVICE_SECRET
        generateValue: true
      - key: EMAIL_SECRET
        generateValue: true
      - key: JWT_PRIVATE_KEY
        generateValue: true
      - key: JWT_REFRESH_PEPPER
        generateValue: true
        
      # Leave these un-synced so Render prompts the User to supply their keys when deploying
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
        
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false

databases:
  - name: dwellly-db
    databaseName: dwellly_db
    user: dwellly_db_user
    plan: free
